# If launch in i3/config the scratchpads are not spawn (race condition?)
urxvtd -o -q -f

# merge .Xressources file
[[ -f $XDG_CONFIG_HOME/.Xresources ]] && xrdb -merge -I$XDG_CONFIG_HOME $XDG_CONFIG_HOME/.Xresources

# Run ssh-agent
# trap 'test -n "$SSH_AUTH_SOCK" && eval `/usr/bin/ssh-agent -k`' 0

# maps caps lock to escape for vim 
e setxkbmap -option 'caps:ctrl_modifier' && xcape -e 'Caps_Lock=Escape' &

# personnalized keyboard keys
[[ -f $XDG_CONFIG_HOME/.Xmodmap ]] && xmodmap $XDG_CONFIG_HOME/.Xmodmap

udiskie &

exec i3
