urxvtd -o -q -f

# set the keyboard to mac
setxkbmap us mac
# maps caps lock to escape for vim 
setxkbmap -option 'caps:ctrl_modifier' && xcape -e 'Caps_Lock=Escape' &
xmodmap ~/.Xmodmap

# merge .Xressources file
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# exec vmware tools
vmware-user-suid-wrapper

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# exec i3
exec i3
