#!/usr/bin/env bash

while read file
do
        case "$1" in
        "C-d")
                mkdir -p ~/.trash && mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
                nitrogen --save --set-zoom-fill "$file" ;;
        esac
done
