#!/usr/bin/env bash

# All shortcut needs to be preceded by CTRL-X

while read -r file
do
        case "$1" in
        "C-d")
                mkdir -p "$XDG_CONFIG_HOME/trash" && mv "$file" "$XDG_CONFIG_HOME/trash" ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
                nitrogen --save --set-zoom-fill "$file" ;;
        esac
done
