#!/bin/bash

###################
# STARTUP FOR ZSH #
###################

# zsh sourcing
SCRIPT_PATH="${0:A:h}"

source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
source $DOTFILES/antibody/plugins.sh

# source <(antibody init)
# TODO - need to be executed once after installing... get rid of antibody?
# antibody bundle < $DOTFILES/antibody/plugins.txt
###
# source "${HOME}/.zgen/zgen.zsh"
###

# Config file
# fzf goodies
command -v "fzf" >/dev/null && source $SCRIPT_PATH/zsh/scripts_fzf.zsh
