source ${ZDOTDIR:-$HOME}/.terminal_config/startup

# Vi mode
bindkey -v
export KEYTIMEOUT=1

# Fix bug when prompt has two lines
bindkey -r '^l'
bindkey -r '^g'
bindkey -s '^g' 'clear\n'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

