#!/bin/zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# Change this variable if your dotfiles are not in this path!!!
# Useful for the install scripts
export DOTFILES="$HOME/.dotfiles"

export TERM='rxvt-256color'

export EDITOR="nvim"
export VISUAL="nvim"

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

# Variable for software config

export TMUXP_CONFIGDIR="$XDG_CONFIG_HOME/tmuxp"
export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
export I3_CONFIG="$XDG_CONFIG_HOME/i3"
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"

# Modifying the path for ruby gems
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

# PATH for composer global install
PATH="$COMPOSER_HOME/vendor/bin:$PATH"

# PATH for Golang
export GOPATH="$HOME/workspace/go"
export GOBIN="$HOME/workspace/go/bin"
export GOCACHE="$HOME/.cache/go-build"

# PATH for go binaries
PATH="$GOBIN:$PATH"

# Override ls colors
eval "$(dircolors -b $XDG_CONFIG_HOME/.dircolors)"

# Install of global npm packages
export NPMPATH="$HOME/.node_modules"
export NPMBIN="$HOME/.node_modules/bin"
PATH="$NPMBIN:$PATH"
export npm_config_prefix=$XDG_CONFIG_HOME/.node_modules

# See gitconfig
export GIT_REVIEW_BASE=master

# Make dotfile config available in the whole system
if [ -f $DOTFILES/install_config ];
    then
        source $DOTFILES/install_config
fi
