#!/bin/zsh

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export TERM='rxvt-256color'
export DOTFILES="$HOME/.dotfiles"

[ -f $DOTFILES/install_config ] && source $DOTFILES/install_config

# XDG

export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$XDG_CONFIG_HOME/local/share
export XDG_CACHE_HOME=$XDG_CONFIG_HOME/cache

# editor

export EDITOR="nvim"
export VISUAL="nvim"

# zsh

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"    # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# other software

export TMUXP_CONFIGDIR="$XDG_CONFIG_HOME/tmuxp"
export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
export I3_CONFIG="$XDG_CONFIG_HOME/i3"
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"

# Modifying the path for ruby gems
# PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

# golang

export GOPATH="$HOME/workspace/go"
export GOBIN="$HOME/workspace/go/bin"
export GOCACHE="$XDG_CACHE_HOME/go-build"

# npm

export NPM_PATH="$XDG_CONFIG_HOME/node_modules"
export NPM_BIN="$XDG_CONFIG_HOME/node_modules/bin"
# export npm_config_prefix=$XDG_CONFIG_HOME/node_modules

# git
export GIT_REVIEW_BASE=master # See gitconfig

# PATH

PATH="$COMPOSER_HOME/vendor/bin:$PATH"
PATH="$GOBIN:$PATH"
PATH="$NPM_BIN:$PATH"


