source ${ZDOTDIR:-$HOME}/.dotfiles/startup

# edit current command line with vim
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# Vi mode
bindkey -v
export KEYTIMEOUT=1

# use ripgrep with fzf
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Search with fzf and open selected file with Vim
bindkey -s '^v' 'vim $(fzf);^M'

# Fix bug when prompt has two lines
bindkey -r '^l'
bindkey -r '^g'
bindkey -s '^g' 'clear\n'
bindkey -r '^p'
bindkey -s '^p' 'fmux\n'

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# open man page in vim
vman() {
    nvim -c "SuperMan $*"

    if [ "$?" != "0" ]; then
        echo "No manual entry for $*"
    fi
}

if [[ "$(tty)" = "/dev/tty1" ]];
then
    pgrep i3 || exec ssh-agent startx
fi

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

# Display all possible tmuxp session when opening terminal
ftmuxp
